namespace UrlShortener.Api.Controllers;

internal static class RedirectHtmlPages
{
    public static string NotFound(string shortCode, string message)
        => Render(
            title: "Link not found",
            headline: "This short link doesn't exist",
            body: $"Code <b>/{Escape(shortCode)}</b> is not available. {Escape(message)}",
            badge: "404");

    public static string Gone(string shortCode, string message, DateTimeOffset? expiresAt)
    {
        var expiredAtHtml = expiresAt.HasValue
            ? $"<div class=\"muted\">Expired at: {expiresAt:yyyy-MM-dd HH:mm} UTC</div>"
            : string.Empty;

        return Render(
            title: "Link expired",
            headline: "This short link has expired",
            body: $"Code <b>/{Escape(shortCode)}</b> is no longer active. {Escape(message)}{expiredAtHtml}",
            badge: "410");
    }

    private static string Render(string title, string headline, string body, string badge)
    {
        var lines = new[]
        {
            "<!doctype html>",
            "<html lang=\"en\">",
            "<head>",
            "  <meta charset=\"utf-8\" />",
            "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />",
            $"  <title>{Escape(title)}</title>",
            "  <style>",
            "    * {",
            "      margin: 0;",
            "      padding: 0;",
            "      box-sizing: border-box;",
            "    }",
            "    body {",
            "      background: #f5f5f5;",
            "      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;",
            "      min-height: 100vh;",
            "      display: flex;",
            "      align-items: center;",
            "      justify-content: center;",
            "      padding: 20px;",
            "    }",
            "    .card {",
            "      background: white;",
            "      border-radius: 12px;",
            "      box-shadow: 0 2px 8px rgba(0,0,0,0.08);",
            "      padding: 32px;",
            "      max-width: 560px;",
            "      width: 100%;",
            "      border: 1px solid #e0e0e0;",
            "    }",
            "    .header {",
            "      display: flex;",
            "      align-items: center;",
            "      justify-content: space-between;",
            "      margin-bottom: 24px;",
            "      padding-bottom: 16px;",
            "      border-bottom: 1px solid #eee;",
            "    }",
            "    .logo {",
            "      font-weight: 600;",
            "      font-size: 18px;",
            "      color: #1a1a1a;",
            "    }",
            "    .badge {",
            "      font-size: 13px;",
            "      padding: 4px 10px;",
            "      border-radius: 20px;",
            "      background: #f0f0f0;",
            "      color: #666;",
            "      font-family: monospace;",
            "      font-weight: 500;",
            "    }",
            "    h1 {",
            "      font-size: 24px;",
            "      font-weight: 600;",
            "      color: #1a1a1a;",
            "      margin-bottom: 12px;",
            "    }",
            "    p {",
            "      color: #555;",
            "      line-height: 1.5;",
            "      font-size: 15px;",
            "      margin-bottom: 8px;",
            "    }",
            "    .muted {",
            "      color: #888;",
            "      font-size: 13px;",
            "      margin-top: 8px;",
            "    }",
            "    .actions {",
            "      margin-top: 24px;",
            "      display: flex;",
            "      gap: 12px;",
            "      flex-wrap: wrap;",
            "    }",
            "    .btn {",
            "      display: inline-flex;",
            "      align-items: center;",
            "      padding: 8px 18px;",
            "      border-radius: 6px;",
            "      text-decoration: none;",
            "      font-size: 14px;",
            "      font-weight: 500;",
            "      transition: all 0.2s;",
            "    }",
            "    .btn-primary {",
            "      background: #1a1a1a;",
            "      color: white;",
            "      border: 1px solid #1a1a1a;",
            "    }",
            "    .btn-primary:hover {",
            "      background: #333;",
            "    }",
            "    .btn-secondary {",
            "      background: white;",
            "      color: #555;",
            "      border: 1px solid #ddd;",
            "    }",
            "    .btn-secondary:hover {",
            "      background: #f5f5f5;",
            "      border-color: #ccc;",
            "    }",
            "    .footer {",
            "      margin-top: 24px;",
            "      padding-top: 16px;",
            "      border-top: 1px solid #eee;",
            "      font-size: 12px;",
            "      color: #999;",
            "    }",
            "  </style>",
            "</head>",
            "<body>",
            "  <div class=\"card\">",
            "    <div class=\"header\">",
            "      <span class=\"logo\">🔗 GlassLink</span>",
            $"      <span class=\"badge\">{Escape(badge)}</span>",
            "    </div>",
            string.Empty,
            $"    <h1>{Escape(headline)}</h1>",
            $"    <p>{body}</p>",
            string.Empty,
            "    <div class=\"actions\">",
            "      <a class=\"btn btn-primary\" href=\"/health\">API Health</a>",
            "      <a class=\"btn btn-secondary\" href=\"javascript:history.back()\">Go Back</a>",
            "    </div>",
            "    <div class=\"footer\">",
            "      If you believe this is a mistake, contact the link owner.",
            "    </div>",
            "  </div>",
            "</body>",
            "</html>"
        };

        return string.Join(Environment.NewLine, lines);
    }

    private static string Escape(string value)
        => System.Net.WebUtility.HtmlEncode(value);
}